version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
    build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      #      - run:
      #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
      #         command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          when: always
      - run:
          name: Run Unit Tests against Presenter
          command: ./gradlew clean lint test jacocoTestReport


      - codecov/upload:
          file: $buildDir/reports/jacoco